package netway

const (

	CLOSE_SOURCE_CLIENT = 1			//客户端断开连接
	CLOSE_SOURCE_AUTH_FAILED = 2	//服务端验证失败
	CLOSE_SOURCE_CREATE = 3			//初始化 连接类失败，可能是连接数过大
	CLOSE_SOURCE_CLIENT_PRE = 4		//C端主动，预先关闭
	CLOSE_SOURCE_OVERRIDE = 5		//创建新连接时，发现，该用户还有一个未关闭的连接
	CLOSE_SOURCE_TIMEOUT = 6		//最后更新时间 ，超时
	CLOSE_SOURCE_SIGNAL_QUIT = 7 	//接收到关闭信号
	CLOSE_SOURCE_CLIENT_WS_FD_GONE = 8	//客户端异常关闭了
	CLOSE_SOURCE_FD_READ_EMPTY = 9	//首次建立连接时，获取token为空
	CLOSE_SOURCE_FD_READ_ERR = 10	//首次建立连接时，read出错
	CLOSE_SOURCE_FD_PARSE_CONTENT = 11	//首次建立连接时，解析内容时出错
	CLOSE_SOURCE_FIRST_NO_LOGIN = 12	//


	CONTENT_TYPE_JSON = 1			//内容类型 json
	CONTENT_TYPE_PROTOBUF = 2		//proto_buf

	CONN_STATUS_WAITING = 1
	CONN_STATUS_EXECING = 2		//
	CONN_STATUS_CLOSE = 3

	PROTOCOL_SOCKET = 1
	PROTOCOL_WEBSOCKET = 2

	ROOM_STATUS_INIT = 1
	ROOM_STATUS_EXECING = 2
	ROOM_STATUS_END = 3
	ROOM_STATUS_READY = 4
	ROOM_STATUS_PAUSE = 5

	//一个副本的整体状态
	//SYNC_ELEMENT_STATUS_WAIT = 1
	//SYNC_ELEMENT_STATUS_EXECING = 2
	//SYNC_ELEMENT_STATUS_END = 3

	//一个副本的，一条消息的，同步状态
	PLAYERS_ACK_STATUS_INIT = 1
	PLAYERS_ACK_STATUS_WAIT = 2
	PLAYERS_ACK_STATUS_OK = 3


	PLAYER_STATUS_ONLINE = 1
	PLAYER_STATUS_OFFLINE = 2

	LOCK_MODE_PESSIMISTIC = 1
	LOCK_MODE_OPTIMISTIC = 2
)

